### ISSUE TITLE
Add Get client candidate by ID call

### ISSUE THREAD

**Issue by badluck13** [DoddleNow/DoddleNow-BackEnd#19]
It's similar to Get client job candidate by ID, but this will just return a specific candidate not connected to any job entity:

Here is how request looks for **Get client job candidate by ID**: `GET /api/v1/ha/{clientId}/jobs/{jobId}/candidates/{candidateId}`

We need one that is not connected to job **Get client candidate by ID**: `GET /api/v1/ha/{clientId}/candidates/{candidateId}`

We already have list of all candidates on: `GET /api/v1/ha/{clientId}/candidates` we just need to get specific candidate from it.

**Comment by badluck13** [comment]
This is related to DoddleNow/DoddleNow-FrontEnd#49 issue

**Comment by badluck13** [comment]
This two GET calls should return the same info:
`
GET {{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/jobs/0a18a498-442a-4705-b525-0cc99e0a4f8e/candidates/d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b
`
and
`
GET {{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/candidates/d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b
`
Also we forgot that there should be a corresponding POST call
`
POST {{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/candidates/d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b
`
That would work the same as:
`
POST {{url}}/api/v1/HA/5d85285d-401b-4b12-8692-db70e81df0b3/jobs/0a18a498-442a-4705-b525-0cc99e0a4f8e/candidates/d0fbb274-f20d-4611-a7a0-6a7ea99dfa2b
`

**Comment by johnnymagic** [comment]
This one starts to break the data model so I'd like to figure out where it is intended and if we need to change anything.

When we say "candidateId", it is the userId of the HP.  They may have applied to multiple jobs under a client.  If we ask for a client candidate, it should show the client profile and and 1 to many jobs underneath that client, correct?

Same for the POST.  I need to know the jobId to add these properties  (starred) because they may be interested in the HP for one job but not the other.

If you tell me what the intent is and how the screen will behave, we can come up with the right data to return.
